name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Sử dụng Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - name: Tạo thư mục dữ liệu cho SQLite
        run: mkdir -p ${{ github.workspace }}/data

      - name: Chạy kiểm tra với biến môi trường SQLITE_DB_LOCATION
        run: npm test
        env:
          SQLITE_DB_LOCATION: ${{ github.workspace }}/data/todo.db
